---
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  yamllint
platforms:
  - name: instance
    box: ubuntu/xenial64
    provider_raw_config_args:
    - "customize [ 'modifyvm', :id, ' --uartmodel', 'disconnected,]"
provisioner:
  name: ansible
  lint:
    name: ansible-lint
